### ISSUE TITLE
errormsg pops up by saving

### ISSUE THREAD

**Issue by mjrd0815** [rstarkov/TankIconMaker#11]
hello together,

i have now windows 11 and alos newly downloaded the TankIconMaker.
by trying to save the newly created TankIcons a get an error:
![image](https://user-images.githubusercontent.com/103564438/210148919-ada8b2e1-eb60-4103-8213-ab786e4fbe7c.png)

both Files are in the directory and also the ***64.dll is fresh downloaded and copied in the folder
![image](https://user-images.githubusercontent.com/103564438/210148982-911c719e-e0d0-4976-9634-82efaf92ccd5.png)

any body an idea whats wrong here?
google dosnt help me here.

**Comment by AstaRom** [comment]
The system requirements for the program have not been met. You can find them on the [project page](https://roman.st/TankIconMaker) .

Namely, not installed:

- [VC++ 2013 Redistributable](https://www.microsoft.com/en-gb/download/details.aspx?id=40784)

**Comment by mjrd0815** [comment]
> The system requirements for the program have not been met. You can find them on the [project page](https://roman.st/TankIconMaker) .
> 
> Namely, not installed:
> 
> * [VC++ 2013 Redistributable](https://www.microsoft.com/en-gb/download/details.aspx?id=40784)

so no TankIconMNaker for Win11?

good damit... but thank you! :)

**Comment by AstaRom** [comment]
TIM operation does not depend on the system version, it is fully functional on all versions with Win XP and later. To work, only the additional components indicated on the site are required.

**Comment by mjrd0815** [comment]
> TIM operation does not depend on the system version, it is fully functional on all versions with Win XP and later. To work, only the additional components indicated on the site are required.

thank you!
and of course u are right...

* [VC++ 2013 Redistributable](https://www.microsoft.com/en-gb/download/details.aspx?id=40784)

this was missing. :)
