### ISSUE TITLE
got an error today after the patch.

### ISSUE THREAD

**Issue by mjrd0815** [rstarkov/TankIconMaker#12]
Thread: Main

Exception: WotDataLib.WotDataException
Message: Could not parse game data for country "uk"
  ...
  bei TankIconMaker.MainWindow.ReloadData(Boolean first) in MainWindow.xaml.cs:Zeile 399.

Exception: WotDataLib.WotDataException
Message: Could not parse game data for country "GB121_GSOR_1010_FB"
  ...

Exception: System.Collections.Generic.KeyNotFoundException
Message: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
  ...

**Comment by arsenal3008** [comment]
> A new version is available for download.
I don't see where

**Comment by AstaRom** [comment]
- https://github.com/rstarkov/TankIconMaker/releases/tag/release-v067

**Comment by mjrd0815** [comment]
thank you so much! <3
