### ISSUE TITLE
113 BO icon failure

### ISSUE THREAD

**Issue by mjrd0815** [rstarkov/TankIconMaker#13]
i have made my own icon for tankcontours.
but the 113 BO refuse to work with it. :)

![113 BO](https://github.com/rstarkov/TankIconMaker/assets/103564438/45d7a4fe-471d-4930-af8d-3e83f883081c)

**Comment by AstaRom** [comment]
It was on the exclusion list because it was only on the Asian server.
Edit the "[WotBuiltIn-1.csv" file or download a new build:

- https://ci.appveyor.com/api/buildjobs/r43ye2avu4qefq6p/artifacts/TankIconMaker-v067-b231.zip
