### ISSUE TITLE
Cannot Save BattleAlas in the new update 1.22.1

### ISSUE THREAD

**Issue by LeeShawran** [rstarkov/TankIconMaker#15]
At the moment, the build v067 b230 can't save BattleAlas, when I click the button, the Saving dialog appears but then, there is an error message, it says "Unable to place images in the atlas "[icon_style_name]". Try reducing the size of the images or resizing the atlas. See item "More" > "Atlas width|height". 
After that, there is only battleAtlas.xml file.

I suspect that new elite system conflict the icon
![image](https://github.com/rstarkov/TankIconMaker/assets/19680678/a7251447-4056-4435-b7c1-43f7d917aaa3)

**Comment by AstaRom** [comment]
Increase the size of the atlas canvas; the required options are indicated in the error description.

**Comment by LeeShawran** [comment]
oh, it works, I've increased atlas canvas 5000x5000, thank you very much
