### ISSUE TITLE
Can't load icon

### ISSUE THREAD

**Issue by LeeShawran253** [rstarkov/TankIconMaker#2]
Hi man, I got this problem, I tried to re-install the game file but it's still there, please help

Thread: Main

Exception: WotDataLib.WotDataException
Message: Could not parse game data for country "ussr"
  ...
  at TankIconMaker.MainWindow.ReloadData(Boolean first) in MainWindow.xaml.cs:line 398

Exception: System.InvalidOperationException
Message: String must represent an integer, but "54.06" has a fractional part.
  ...

**Comment by LeeShawran253** [comment]
I'm using v061 b201

**Comment by AstaRom** [comment]
Update TIM, the specified version is out of date.
