### ISSUE TITLE
"Armor/Hull" property shows front thickness instead of rear thickness

### ISSUE THREAD

**Issue by 43615** [rstarkov/TankIconMaker#8]
Armor/Turret is unaffected.
Screenshot:
![image](https://user-images.githubusercontent.com/53740368/168082005-ff2dea49-5b7c-4637-9a2b-2b054d0dc89b.png)

**Comment by AstaRom** [comment]
Fixed:

- https://github.com/rstarkov/WotDataLib/pull/9
