### ISSUE TITLE
Does not work with 1.19.0.3917

### ISSUE THREAD

**Issue by 43615** [rstarkov/TankIconMaker#9]
![image](https://user-images.githubusercontent.com/53740368/205212952-6b8dba45-d831-4d61-9b2d-03915b336cc3.png)

**Comment by 43615** [comment]
Fix found here: https://kr.cm/f/t/33221/c/530132/
A permanent solution would still be nice.

**Comment by s0urcelab** [comment]
> ![image](https://user-images.githubusercontent.com/53740368/205212952-6b8dba45-d831-4d61-9b2d-03915b336cc3.png)

same here.
i can't find any logs, only get this error message.
